[package]
name = "moi"
version = "0.1.1"
authors = ["steve donovan <steve.j.donovan@gmail.com>"]

[dependencies]
json = "0.11.12"
mosquitto-client = "0.1.2"
lapp = "0.3.1"
toml = "0.4.5"
get_if_addrs = "0.4.1"



