help = "installing Debian package"
stages = 4
filter = "$(2:package).not.$(2:version)"

[1]
command = "push"
args = ["$2","tmp"]

[2]
alias = "$1"

[3]
command = "wait"
args = []

[4]
command = "set"
args = ["$(2:package)=$(2:version)"]
